const actionTypes = {
    //product actions start 
    PRODUCTS_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCTS_LIST_SUCESS: 'PRODUCT_LIST_SUCESS',
    PRODUCTS_LIST_FAIL: 'PRODUCT_LIST_FAIL',
    PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
    PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
    PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
    PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',

    USER_LOGIN_LOGOUT: "USER_LOGIN_LOGOUT ", 
    USER_DETAILS_RESET: "USER_DETAILS_RESET ",
    ORDER_LIST_MY_RESET: "ORDER_LIST_MY_RESET", 
    USER_LIST_RESET: "USER_LIST_RESET" 
    
}

export default actionTypes;